version: "3.7"
services:
  mysql:
    image: mysql:8.0
    container_name: cloud-mysql
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
  wordpress:
    image: jamesgreenaway/wordpress:latest
    container_name: cloud-wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: ${COMPOSE_PROJECT_NAME}
      SITE_URL: https://${COMPOSE_PROJECT_NAME}.test
    volumes:
      - ./wordpress:/var/www/html/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud-wordpress.entrypoints=http"
      - "traefik.http.routers.cloud-wordpress.rule=Host(`cloud.test`, `www.cloud.test`)"
      - "traefik.http.middlewares.cloud-wordpress-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.cloud-wordpress.middlewares=cloud-wordpress-https-redirect"
      - "traefik.http.routers.cloud-wordpress-secure.entrypoints=https"
      - "traefik.http.routers.cloud-wordpress-secure.rule=Host(`cloud.test`, `www.cloud.test`)"
      - "traefik.http.routers.cloud-wordpress-secure.tls=true"
      - "traefik.http.routers.cloud-wordpress-secure.tls.certresolver=http"
      - "traefik.http.routers.cloud-wordpress-secure.service=cloud-wordpress"
      - "traefik.http.services.cloud-wordpress.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"
    depends_on:
      - mysql
    networks:
      - default
      - proxy
volumes:
  mysql: {}
networks:
  proxy:
    external: true