version: "3.7"
services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.6
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:5000
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamic_conf.yml:/config/dynamic_conf.yml:ro
      - ./certificates:/certificates:ro
      - ./traefik.yml:/traefik.yml:ro
    # command:
    #   --entrypoints.web.address=:5000
    #   --providers.docker=true
    #   --providers.docker.network=proxy
    #   --entrypoints.web-secure.address=:443
    #   --providers.file.filename=/config/dynamic_conf.yml
    #   --providers.file.watch=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.spinner.test`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:admin"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.spinner.test`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
networks:
  proxy:
    external: true