name: ci

on:
  push:
    branches:
      - '1.x'
    tags: 
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        uses: olegtarasov/get-tag@v2.1
        id: tagName
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            amirmasoud/services:latest
            amirmasoud/services:$GIT_TAG_NAME
